name: deploy gh-pages

on: 
  push:
    branches: 
      - master

jobs:
  build:
    name: Build and deploy gh-pages
    env:
      MY_SECRET   : ${{secrets.commit_secret}}
      USER_NAME   : yoyowarm
      USER_EMAIL  : po8867@gmail.com
      PUBLISH_DIR : ./dist
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install
      run: |
        npm install
    - name: npm run build
      run: |
        npm run build
    - name: Commit files
      run: |
        cd $PUBLISH_DIR
        git init
        git config --local user.email $USER_NAME
        git config --local user.name $USER_EMAIL
        git status
        git remote add origin https://$MY_SECRET@github.com/$GITHUB_REPOSITORY.git
        git checkout -b gh-pages
        git add --all
        git commit -m "deploy to Github pages"
        git push origin gh-pages -f
        echo 🤘 deploy gh-pages complete.
